Repository vattenbagarna/Backend, pull requests merged in 2019-04, with the labels that each got.

#47 User login system
  .gitignore
  API_DOC.md
  config/emailConfig.example.js
  index.js
  middleware/authValidator.js
  package-lock.json
  package.json
  router/admin.js
  router/login.js
  setup/createCollections.js
  src/dbWrapper.js
  src/jwtAuthentication.js
  src/loginHandler.js
  src/smtpMailman.js
Labels: Sprint 3

#55 add return username on sucessful login
  router/login.js
Labels: Sprint 4

#57 add /user/all route
  API_DOC.md
  index.js
  router/user.js
  src/userHandler.js
Labels: Sprint 4

#61 UID from token instead of URL
  API_DOC.md
  router/objects.js
  router/projects.js
Labels: Sprint 4

#64 Updated pumps to insert.
  setup/insertObjects.js
Labels: bug

#66 Fixed syntax error for adding the needed pumps
  setup/insertObjects.js
Labels: bug

#73 Optimize handling
  index.js
  router/admin.js
  src/jwtAuthentication.js
  src/loginHandler.js
Labels: Sprint 4

#75 Updated names and values for pumps and pumpstations
  setup/insertObjects.js
Labels: bug, fix

#77 Fixed insert of kompost 61, 81, 92
  setup/insertObjects.js
Labels: fix

#84 Base64
  setup/insertObjects.js
  setup/setup.sh
Labels: Sprint 5, enhancement
