Repository vattenbagarna/Backend, pull requests merged in 2019-05, with the labels that each got.

#88 Updated pumpcurve for various pumps
  setup/insertObjects.js
Labels: Sprint 5, fix

#90 Updated structure for icon list in database
  setup/insertObjects.js
Labels: Sprint 5, fix

#96 Update icons
  setup/insertObjects.js
Labels: Sprint 6

#98 Removed whitespaces in pump names
  setup/insertObjects.js
Labels: bug, fix

#111 Updated npm
  .eslintignore
  package-lock.json
Labels: fix

#112 added forgotten npm packages
  package-lock.json
  package.json
Labels: fix

#116 added verify login route
  API_DOC.md
  router/user.js
Labels: bug, fix
